
version: "3.9"

services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    hostname: 3x-ui
    volumes:
      - ./dbvless/:/etc/x-ui/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    restart: always
   # ports:
      #- 2053:2053
networks:
  default:
    name: nginxproxymanager_default
    external: true

