---
version: "3.9"

services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    hostname: 3x-ui
    volumes:
      - $PWD/db/:/etc/x-ui/
          environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    restart: always
    ports:
      - 172.17.0.1:443:443
